### ISSUE TITLE
Single page app

### ISSUE THREAD

**Issue by lindell** [phixofor/unvis.it#8]
After making the changes to move out code from index.php it was not very hard to load only the content via ajax requests.

The loading is now looking [like this](https://gfycat.com/TiredFavoriteInsect).
The video is of loading with a 500ms emulated ping.

Feedback wanted on this.

**Comment by lindell** [comment]
I can add that the page load exactly like before when you don't use the input box but coming to the page via direct link.

**Comment by lindell** [comment]
[Changed some more bits in the design and fixed history](https://gfycat.com/NewWhimsicalHoverfly)

**Comment by phixofor** [comment]
Thank you for your efforts! We are in a crunch mode at work and I will review everything as soon as things settle down around next week.

**Comment by phixofor** [comment]
Okay, I have had some time to look at this (going through things that are quickest first because of the crunch mode). I really appreciate your involvement!

At this moment I do not want to increase the branding of the web page, so that logo serves little purpose and takes up a lot of space, in my opinion.

I want to ask you to argue why and how ajax requests would improve the page? Maybe I am limited in knowledge, but it seems like it adds an extra layer, which needs history to be "fixed", that doesn't deliver any upside? The system reports the CPU usage to be really low, bandwidth is also at a 0.35% of the max. So, please enlighten me :)

**Comment by phixofor** [comment]
Closing issue because of lack of input
